name: mecon_limited
description: MECON InfoCentre Mobile Application
publish_to: 'none' # Remove this if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  table_calendar: ^3.0.9
  http: ^1.2.2
  shared_preferences: ^2.3.4
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  jwt_decoder: ^2.0.1
  double_back_to_close: ^2.0.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  intl: ^0.20.2   # ✅ matches Flutter SDK requirement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/attendance.png
    - assets/icons/payslip.png
    - assets/icons/pension.png
    - assets/icons/timecard.png
    - assets/icons/bharti.png
    - assets/icons/calendar.png
    - assets/icons/paybill.png
    - assets/icons/circular.png
    - assets/icons/mecon2.png
    - assets/icons/programmes.png
    - assets/icons/techquest.png
    - assets/icons/mecon.png

  generate: true